### PR TITLE
main.py

### PR DESCRIPTION
**Pull request by trraney328**
this is based off the game

### CODE REVIEW

**Comment by CyberHacker101** [comment]
> this is based off the game

Hello

**Comment by trraney328** [comment]
hi

**Comment by CyberHacker101** [comment]
I’m getting used to git hub

**Comment by trraney328** [comment]
well okay, hey don't do anything but ima get the discussion up and going okay?

**Comment by CyberHacker101** [comment]
K I’m be back when are u free?

**Comment by trraney328** [comment]
okay I got the discussion going now

**Comment by CyberHacker101** [comment]
Brb in a min

**Comment by trraney328** [comment]
okay

**Comment by trraney328** [comment]
go to the discussion I got started

**Comment by trraney328** [comment]
hey, you can review this for me, okay?

**Comment by CyberHacker101** [comment]
Sure

**Comment by trraney328** [comment]
okay

**Comment by CyberHacker101** [comment]
How do i do that😅

**Comment by trraney328** [comment]
okay I assigned you

**Comment by CyberHacker101** [comment]
Ummm

**Comment by CyberHacker101** [comment]
idk

**Comment by trraney328** [comment]
what?

**Comment by trraney328** [comment]
look there is gonna be a review box click that okay?

**Comment by CyberHacker101** [comment]
How do i "review this"

**Comment by trraney328** [comment]
and it'll put a check mar on it okay?

**Comment by trraney328** [comment]
click on my work and you see the review

**Comment by trraney328** [comment]
brb, okay?

**Comment by CyberHacker101** [comment]
kkkk

**Comment by trraney328** [comment]
hey

**Comment by trraney328** [comment]
you see the triangle?

**Comment by trraney328** [comment]
I am back

**Review by trraney328 — COMMENTED** [review]
done

**Comment by CyberHacker101** [comment]
hey bro

**Review by trraney328 — COMMENTED** [review]
its done now

**Comment by trraney328** [comment]
hey cyberhacker101?

**Comment by trraney328** [comment]
accept the review request, ok?

**Review by trraney328 — COMMENTED** [review]
you need to review this @cyberhacker101

**Pull request merged**
