### PR TITLE
Python.txt

### PR DESCRIPTION
**Pull request by trraney328**
this is based off the words for the snowman hang man game

### CODE REVIEW

**Comment by trraney328** [comment]
hey

**Comment by CyberHacker101** [comment]
OOOOOOOf i was busy

**Comment by trraney328** [comment]
I know

**Comment by trraney328** [comment]
are you ready to review this?

**Comment by trraney328** [comment]
because, it's ready to be reviewed

**Comment by trraney328** [comment]
its for my school work

**Pull request closed without merging**
